export const datas = [
  {
    age: 1924,
    civilite: 'F',
    dateOuverture: '2019-01-10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 1,
    numeroRg: '651654654',
    status: 'Eteindre mesure',
    type: 'Tutelle aux biens et à la personne',
    ville: 'PARIS',
  },
  {
    age: 1924,
    civilite: 'F',
    dateOuverture: '2007-06-05',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 2,
    numeroRg: '651654654',
    status: 'Mesure en attente',
    type: 'Curatelle renforcée aux biens et à la personne',
    ville: 'PARIS',
  },
  {
    age: 1986,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 3,
    numeroRg: '651654654',
    status: 'Mesure en cours',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1927,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 7,
    numeroRg: '651654654',
    status: 'Mesure en cours',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1985,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 4,
    numeroRg: '651654654',
    status: 'Mesure en cours',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1988,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 5,
    numeroRg: '651654654',
    status: 'Mesure en cours',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1985,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 6,
    numeroRg: '651654654',
    status: 'Mesure en cours',
    type: 'Tutelle',
    ville: 'PARIS',
  },
];

export const mandataireDatas = [
  {
    age: 1998,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 3,
    numeroRg: '651654654',
    status: 'Mesure en attente',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1998,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 7,
    numeroRg: '651654654',
    status: 'Mesure en attente',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1998,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 4,
    numeroRg: '651654654',
    status: 'Mesure en attente',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1998,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 5,
    numeroRg: '651654654',
    status: 'Mesure en attente',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1998,
    civilite: 'F',
    dateOuverture: '2011-01-11',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 6,
    numeroRg: '651654654',
    status: 'Mesure en attente',
    type: 'Tutelle',
    ville: 'PARIS',
  },
];
